name: Release mkdocs_render_swagger_plugin

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build wheel
        run: pip wheel .
      - name: Install package locally for verification
        run: pip install .
      - name: Verify version
        run: |
          PY_VER=$(python -c "import render_swagger;print(render_swagger.__version__)")
          echo Python version - "$PY_VER"
          TAG_VER=$(echo ${{ github.event.release.tag_name }})
          echo Tag version "$TAG_VER"
          [[ $TAG_VER == $PY_VER ]]
          CFG_VER=$(grep version setup.cfg | cut -d '=' -f2 | xargs)
          echo Config version "$CFG_VER"
          [[ $CFG_VER == $PY_VER ]]
      - name: Install twine
        run: pip install twine
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'mkdocs_render_swagger_plugin-*.whl'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on Test PyPi
        run: twine upload -r testpypi -u ${{ secrets.TEST_PYPI_USERNAME }} -p ${{ secrets.TEST_PYPI_PASSWORD }} mkdocs_render_swagger_plugin-*.whl